### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Justman10000**

### CODE REVIEW

**Comment by angusmcleod** [comment]
@Justman10000 Thanks for the PR! There's no need to change the locale keys `verifiable_credentials.error` and `verifiable_credentials.error_return`. When that's switched back, happy to merge this 👍

**Comment by Justman10000** [comment]
> There's no need to change the locale keys `verifiable_credentials.error` and `verifiable_credentials.error_return`.

However, I have done it because it is possibly more understandable

**Comment by Justman10000** [comment]
@angusmcleod

**Comment by angusmcleod** [comment]
@Justman10000 Happy to merge once the changes are made

> There's no need to change the locale keys verifiable_credentials.error and verifiable_credentials.error_return. When that's switched back, happy to merge this 👍

Plugins need to namespace locales.

**Comment by Justman10000** [comment]
> @Justman10000 Happy to merge once the changes are made
> 
> > There's no need to change the locale keys verifiable_credentials.error and verifiable_credentials.error_return. When that's switched back, happy to merge this 👍
> 
> Plugins need to namespace locales.

???

**Comment by Justman10000** [comment]
It is completely irrelevant what code name one takes?

**Comment by angusmcleod** [comment]
In a plugin in an ecosystem of code you don't control name-spacing is indeed unite relevant for a few reasons. You're welcome to fork the plugin if you'd prefer to take a different approach. This is the approach we're taking in this plugin.

**Comment by angusmcleod** [comment]
In a plugin in an ecosystem of code you don't control name-spacing is indeed unite relevant for a few reasons. You're welcome to fork the plugin if you'd prefer to take a different approach. This is the approach we're taking in this plugin.

**Comment by Justman10000** [comment]
Surely it doesn't matter whether you use _verifiable_credentials_ or _error_ as namespace? Who cares? The main thing is that the module works! And extremely few to none look into the source code!

**Comment by angusmcleod** [comment]
Mate arguing with the maintainer of something you're trying to PR over a few lines of code is not a great idea. Name-spacing locales does indeed matter in Discourse. You can either comply, or we can close this PR.

**Comment by Justman10000** [comment]
Better?

**Comment by angusmcleod** [comment]
Thanks. And thanks for the PR.

**Pull request merged**
